# Generated by Django 5.2 on 2025-04-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_medicalhistory_id_alter_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='disease',
            new_name='diagnosis',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
