# Generated by Django 5.2 on 2025-04-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_disease_medicalhistory_diagnosis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
