# Generated by Django 5.2 on 2025-04-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
